print('Hola, ¿como te llama y cuál es tu edad?')
print('Nombre')
nombre=input()
print('Apellido1')
Apellido1=input()
print('Apellido2')
Apellido2=input()
print('Edad')
Edad=input()
print('El otro día ' + nombre + ' ' + Apellido1 + ' ' + Apellido2 + ' de ' + Edad + ' años, fue encontrado en su casa jugando a la consola en lugar de ir a trabajar.')